slimpay_notification:
    path:  /slimpay/notification
    defaults: { _controller: SlimpayBundle:Notification:slimpayNotification}

slimpay_test_entry_point:
    path:  /slimpay/entry_point
    defaults: { _controller: SlimpayBundle:Test:testEntryPointResource}

slimpay_test_create_mandate:
    path:  /slimpay/create_mandate
    defaults: { _controller: SlimpayBundle:Test:testCreateMandate}

slimpay_test_get_mandates:
    path:  /slimpay/get_mandates
    defaults: { _controller: SlimpayBundle:Test:testGetMandates}

slimpay_test_direct_order:
    path:  /slimpay/create_direct_order
    defaults: { _controller: SlimpayBundle:Test:testCreateDirectOrder}

slimpay_test_get_direct_debit:
    path:  /slimpay/get_direct_debit
    defaults: { _controller: SlimpayBundle:Test:testGetDirectDebits}

slimpay_test_get_orders:
    path:  /slimpay/get_orders
    defaults: { _controller: SlimpayBundle:Test:testGetOrders}